services:
  web:
    build: .
    ports:
      - "8000:8000"

    depends_on:
      - db

    environment:
      - MYSQL_DB=mydb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=3306
      # python manage.py runserver

  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root
