services:
  web:
    build: .
    ports:
      - "8000:8000"

    depends_on:
      - db

    environment:
      - DB_NAME=mydb
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=3306

  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root
